// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Returned by the authenticate mutation.
// Content of bearer_token is required to be supplied in
// Authorization Header on all subsequent API calls.
type AuthToken struct {
	// bearer_token contins JWT token string
	BearerToken string `json:"bearer_token"`
}

// Contains information about whether or not an IPV4 address in
// on a blocklist
type DNSBlockListRecord struct {
	// A unique identifier generated by the system for each record
	UUID string `json:"uuid"`
	// Timestamp indicating when the record was first created
	CreatedAt time.Time `json:"created_at"`
	// Timestamp indicating when the record was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// Indicates if the ip_address is on the blocklist
	ResponseCode string `json:"response_code"`
	// IPV4 address of the record
	IPAddress string `json:"ip_address"`
}
